id = "pearl-theme"
name = "Pearl Theme"
version = "0.0.1"
schema_version = 1
authors = ["Ollayor M <muhammadnabiyevolloyor@gmail.com>"]
description = "Pearl - sepia light, charcoal dark."
repository = "https://github.com/olllayor/pearl-theme"
